spring:
  application:
    name: log-mcp-server
  ai:
    mcp:
      server:
        transport: streamable-http
        annotation-scanner:
          enabled: true

server:
  port: 8091

vantage:
  elasticsearch:
    host: localhost
    port: 9200
    username: elastic
    password: ${ES_PASSWORD}