spring:
  application:
    name: log-mcp-server
  ai:
    mcp:
      server:
        name: log-mcp-server
        protocol: STREAMABLE
        annotation-scanner:
          enabled: true
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

server:
  port: 8091

vantage:
  elasticsearch:
    host: localhost
    port: 9200
    username: elastic
    password: ${ES_PASSWORD}