spring:
  application:
    name: code-mcp-server
  ai:
    mcp:
      server:
        protocol: STREAMABLE
        annotation-scanner:
          enabled: true

server:
  port: 8092

vantage:
  opengrok:
    search-url: http://localhost:8080/source/api/v1/search
    source-root: /opengrok/src
